<?php

namespace AppBundle\Repository;

use AppBundle\Entity\{FinanceAccount, FinanceMovement};

/**
 * FinanceAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinanceAccountRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param FinanceAccount $account
     *
     * @return \Doctrine\Common\Collections\ArrayCollection|FinanceMovement[]
     */
    public function getFixedMovements(FinanceAccount $account)
    {
        return $account->getMovements()->filter(function (FinanceMovement $movement) {
            return $movement->isFixed();
        });
    }

    /**
     * @param FinanceAccount $account
     *
     * @return int
     */
    public function getAmount(FinanceAccount $account)
    {
        $amount = $account->getAmount();

        if (!$account->getMovements()->count()) {
            return $amount;
        }

        $fixed = [];

        foreach ($account->getMovements() as $movement) {
            if ($movement->isFixed()) {
                $fixed[] = $movement;
                continue;
            }

            $amount += $movement->getAmount();
        }

        // When in new month, add fixed movements
        if (date('Y-m-d') >= date('Y-m-01')) {
            /** @var FinanceMovement $movement */
            foreach ($fixed as $movement) {
                $amount += $movement->getAmount();
            }
        }

        return $amount;
    }
}
