<?php

namespace AppBundle\Repository;

use AppBundle\Entity\FinanceAccount;
use AppBundle\Entity\FinanceMovement;

/**
 * FinanceAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinanceAccountRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param FinanceAccount $account
     *
     * @return int
     */
    public function getAmount(FinanceAccount $account)
    {
        $amount = $account->getAmount();

        if (!$account->getMovements()->count()) {
            return $amount;
        }

        foreach ($account->getMovements() as $movement) {
            $amount += $movement->getAmount();
        }

        return $amount;
    }
}
