<?php

namespace AppBundle\Repository;

/**
 * FinanceMovementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinanceMovementRepository extends \Doctrine\ORM\EntityRepository
{
}
