<?php

namespace AppBundle\Repository;

use AppBundle\Entity\{FinanceAccount, FinanceMovement};

/**
 * FinanceAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinanceAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
